export const initialState = {
  products: {
    data: [
      {
        id: 1,
        category: 'safe for animals',
        title: 'Plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 3,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 2,
        category: 'exotic',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 5,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 3,
        category: 'safe for animals',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 10,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 4,
        category: 'exotic',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 5,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 5,
        category: 'safe for animals',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 7,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 6,
        category: 'exotic',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 9,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 7,
        category: 'safe for animals',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 3,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 8,
        category: 'exotic',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 4,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 9,
        category: 'safe for animals',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 5,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
      {
        id: 10,
        category: 'exotic',
        title: 'plant1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
        price: 20,
        image: ['/images/products/plant1.jpg', '/images/products/plant1.jpg', '/images/products/plant1.jpg'],
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  categories: {
    data: [
      {
        id: 1,
        name: 'safe for animals',
        title: 'Safe for animals',
        priceMin: 3,
        image: '/images/categories/plant1.jpg',
      },
      {
        id: 2,
        name: 'exotic',
        title: 'Exotic',
        priceMin: 5,
        image: '/images/categories/plant1.jpg',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};